name: CDK Deploy

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Version of Python'
        type: string
        required: true
        default: "3.11"
      node-version:
        description: 'Version of NodeJs'
        type: string
        required: true
        default: "16"
    secrets:
      aws-access-key-id:
        description: 'AWS Account Access Key'
        required: true
      aws-secret-access-key:
        description: 'Aws Account Secret Key'
        required: true


jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python-version }}'
          

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node-version }}'
          cache: "npm"
          cache-dependency-path: '/home/runner/work/aws-cdk/aws-cdk/hello-cdk/package-lock.json'
     # - run: npm install  -g aws-cdk

      - name: Install Python dependencies and CDK
        run: |
          #python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-2"

      - name: Synth stack
        run: cdk synth

      - name: Deploy stack to AWS
        run: cdk deploy --all --require-approval never
