name: "composite action test"

on:
   workflow_dispatch:
   # push:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: shanmukha511/composite-action-poc/setup-composite@v1
        with:
          helmfile-version: '0.161.0'
