name: "composite action test"

on:
   workflow_dispatch:
   # push:
jobs:
  Composite-Action1-Job:
    runs-on: ubuntu-latest
    name: Calling Composite-Action1
    steps:
      - uses: actions/checkout@v2
      - id: helmfile-composite-action
        uses: shanmukha511/composite-action-poc/setup-composite1@main
  Composite-Action2-Job:
    runs-on: ubuntu-latest
    name: Calling Composite-Action2
    steps:
      - uses: actions/checkout@v2
      - id: helm-composite-action
        uses: shanmukha511/composite-action-poc/setup-composite2@main
        with:
          helmfile-version: '3.14.0' 
   
